/*
	Header generated by bsl
*/
#define nameCell                                0
#define nameDate                                1
#define nameFin                                 2
#define nameMath                                3
#define nameStat                                4
#define nameText                                5
#define nameLog                                 6
#define nameEng                                 7
#define namePlug                                8
