/*
	Header generated by bsl
*/
#define menu_InsertRow                          0
#define menu_InsertCol                          1
#define menu_DeleteRow                          2
#define menu_DeleteCol                          3
#define dlg_Key                                 4
#define dlg_Col                                 5
#define dlg_Row                                 6
#define dlg_SortRange                           7
#define dlg_Asc                                 8
#define dlg_Des                                 9
#define dlg_SortRows                           10
#define dlg_SortCols                           11
#define dlg_NoKey                              12
#define dlg_First                              13
#define dlg_Next                               14
#define dlg_Last                               15
#define str_Untitled                           16
