/*
	Header generated by bsl
*/
#define kUndo                                   0
#define kRedo                                   1
#define kEnterCellStrID                         2
#define kStyleStrID                             3
#define kFillDownStrID                          4
#define kFillRightStrID                         5
#define kInsertStrID                            6
#define kDeleteStrID                            7
#define kPasteStrID                             8
#define kCutStrID                               9
#define kClearStrID                            10
#define kDragStrID                             11
#define kFillStrID                             12
#define kDeleteGraph                           13
#define kUndoResizeRow                         14
#define kUndoResizeColumn                      15
#define kSortStrID                             16
#define kEraseStrID                            17
#define kReplaceID                             18
#define kReplaceAllID                          19
#define kDeleteChartID                         20
#define kAddGraphicID                          21
#define kCutChartID                            22
#define kMoveChartID                           23
#define kResizeChartID                         24
#define kChartOptionsID                        25
